spring.application.name=demo

# ▼ PostgreSQL 接続設定（ユーザープロパティ）
spring.datasource.url=jdbc:postgresql://localhost:5432/usermanagement
spring.datasource.username=postgres
spring.datasource.password=postgres

# ▼ JPA（Hibernate）設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ▼ MyBatis 設定
mybatis.mapper-locations=classpath:com/example/demo/repository/*.xml
mybatis.type-aliases-package=com.example.demo.entity


# Disable Spring SQL initialization checks to avoid bean-definition detection issue during startup
spring.sql.init.enabled=false
